export interface RoadSign {
  id: string;
  number: string; // e.g., "1.1", "3.24"
  name: string;
  description: string;
  category:
    | 'warning'
    | 'priority'
    | 'prohibitory'
    | 'mandatory'
    | 'special'
    | 'information'
    | 'service'
    | 'additional';
  image?: string; // Path to image in public folder
  placement?: string; // Placement instructions
}

export const roadSigns: RoadSign[] = [
  // 1. ՆԱԽԱԶԳՈՒՇԱՑՆՈՂ ՆՇԱՆՆԵՐ
  {
    id: '1.1',
    number: '1.1',
    name: 'Երկաթուղային գծանց` ուղեփակոցով',
    description: '1.1. «Երկաթուղային գծանց` ուղեփակոցով»',
    category: 'warning',
    image: '/road-signs/1.1.png',
  },
  {
    id: '1.2',
    number: '1.2',
    name: 'Երկաթուղային գծանց` առանց ուղեփակոցի',
    description: '1.2. «Երկաթուղային գծանց` առանց ուղեփակոցի»',
    category: 'warning',
    image: '/road-signs/1.2.png',
  },
  {
    id: '1.3.1',
    number: '1.3.1',
    name: 'Միագիծ երկաթուղի',
    description: '1.3.1. «Միագիծ երկաթուղի»',
    category: 'warning',
    image: '/road-signs/1.3.1.png',
  },
  {
    id: '1.3.2',
    number: '1.3.2',
    name: 'Բազմագիծ երկաթուղի',
    description: '1.3.2. «Բազմագիծ երկաթուղի»',
    category: 'warning',
    image: '/road-signs/1.3.2.png',
  },
  {
    id: '1.4.1',
    number: '1.4.1',
    name: 'Մոտեցում երկաթուղային գծանցին',
    description: '1.4.1. «Մոտեցում երկաթուղային գծանցին»',
    category: 'warning',
    image: '/road-signs/1.4.1.png',
  },
  {
    id: '1.4.2',
    number: '1.4.2',
    name: 'Մոտեցում երկաթուղային գծանցին',
    description: '1.4.2. «Մոտեցում երկաթուղային գծանցին»',
    category: 'warning',
    image: '/road-signs/1.4.2.png',
  },
  {
    id: '1.4.3',
    number: '1.4.3',
    name: 'Մոտեցում երկաթուղային գծանցին',
    description: '1.4.3. «Մոտեցում երկաթուղային գծանցին»',
    category: 'warning',
    image: '/road-signs/1.4.3.png',
  },
  {
    id: '1.4.4',
    number: '1.4.4',
    name: 'Մոտեցում երկաթուղային գծանցին',
    description: '1.4.4. «Մոտեցում երկաթուղային գծանցին»',
    category: 'warning',
    image: '/road-signs/1.4.4.png',
  },
  {
    id: '1.4.5',
    number: '1.4.5',
    name: 'Մոտեցում երկաթուղային գծանցին',
    description: '1.4.5. «Մոտեցում երկաթուղային գծանցին»',
    category: 'warning',
    image: '/road-signs/1.4.5.png',
  },
  {
    id: '1.4.6',
    number: '1.4.6',
    name: 'Մոտեցում երկաթուղային գծանցին',
    description: '1.4.6. «Մոտեցում երկաթուղային գծանցին»',
    category: 'warning',
    image: '/road-signs/1.4.6.png',
  },
  {
    id: '1.5',
    number: '1.5',
    name: 'Հատում տրամվայի գծի հետ',
    description: '1.5. «Հատում տրամվայի գծի հետ»',
    category: 'warning',
    image: '/road-signs/1.5.png',
  },
  {
    id: '1.6',
    number: '1.6',
    name: 'Հավասարազոր ճանապարհների հատում',
    description: '1.6. «Հավասարազոր ճանապարհների հատում»',
    category: 'warning',
    image: '/road-signs/1.6.png',
  },
  {
    id: '1.7',
    number: '1.7',
    name: 'Հատում շրջանաձև երթևեկության հետ',
    description: '1.7. «Հատում շրջանաձև երթևեկության հետ»',
    category: 'warning',
    image: '/road-signs/1.7.png',
  },
  {
    id: '1.8',
    number: '1.8',
    name: 'Լուսացուցային կարգավորում',
    description: '1.8. «Լուսացուցային կարգավորում»',
    category: 'warning',
    image: '/road-signs/1.8.png',
  },
  {
    id: '1.9',
    number: '1.9',
    name: 'Բացվող կամուրջ',
    description: '1.9. «Բացվող կամուրջ»',
    category: 'warning',
    image: '/road-signs/1.9.png',
  },
  {
    id: '1.10',
    number: '1.10',
    name: 'Ելք դեպի առափ',
    description: '1.10. «Ելք դեպի առափ»',
    category: 'warning',
    image: '/road-signs/1.10.png',
  },
  {
    id: '1.11.2',
    number: '1.11.2',
    name: 'Վտանգավոր շրջադարձ',
    description: '1.11.2. «Վտանգավոր շրջադարձ»',
    category: 'warning',
    image: '/road-signs/1.11.2.png',
  },
  {
    id: '1.12.1',
    number: '1.12.1',
    name: 'Վտանգավոր շրջադարձեր',
    description: '1.12.1. «Վտանգավոր շրջադարձեր»',
    category: 'warning',
    image: '/road-signs/1.12.1.png',
  },
  {
    id: '1.12.2',
    number: '1.12.2',
    name: 'Վտանգավոր շրջադարձեր',
    description: '1.12.2. «Վտանգավոր շրջադարձեր»',
    category: 'warning',
    image: '/road-signs/1.12.2.png',
  },
  {
    id: '1.13',
    number: '1.13',
    name: 'Կտրուկ վայրէջք',
    description: '1.13. «Կտրուկ վայրէջք»',
    category: 'warning',
    image: '/road-signs/1.13.png',
  },
  {
    id: '1.14',
    number: '1.14',
    name: 'Կտրուկ վերելք',
    description: '1.14. «Կտրուկ վերելք»',
    category: 'warning',
    image: '/road-signs/1.14.png',
  },
  {
    id: '1.15',
    number: '1.15',
    name: 'Սայթաքուն ճանապարհ',
    description: '1.15. «Սայթաքուն ճանապարհ»',
    category: 'warning',
    image: '/road-signs/1.15.png',
  },
  {
    id: '1.16',
    number: '1.16',
    name: 'Անհարթ ճանապարհ',
    description: '1.16. «Անհարթ ճանապարհ»',
    category: 'warning',
    image: '/road-signs/1.16.png',
  },
  {
    id: '1.17',
    number: '1.17',
    name: 'Արհեստական անհարթություն',
    description: '1.17. «Արհեստական անհարթություն»',
    category: 'warning',
    image: '/road-signs/1.17.png',
  },
  {
    id: '1.18',
    number: '1.18',
    name: 'Խճի արտանետում',
    description: '1.18. «Խճի արտանետում»',
    category: 'warning',
    image: '/road-signs/1.18.png',
  },
  {
    id: '1.19',
    number: '1.19',
    name: 'Վտանգավոր կողնակ',
    description: '1.19. «Վտանգավոր կողնակ»',
    category: 'warning',
    image: '/road-signs/1.19.png',
  },
  {
    id: '1.20.1',
    number: '1.20.1',
    name: 'Ճանապարհի նեղացում',
    description: '1.20.1. «Ճանապարհի նեղացում»',
    category: 'warning',
    image: '/road-signs/1.20.1.png',
  },
  {
    id: '1.20.2',
    number: '1.20.2',
    name: 'Ճանապարհի նեղացում',
    description: '1.20.2. «Ճանապարհի նեղացում»',
    category: 'warning',
    image: '/road-signs/1.20.2.png',
  },
  {
    id: '1.20.3',
    number: '1.20.3',
    name: 'Ճանապարհի նեղացում',
    description: '1.20.3. «Ճանապարհի նեղացում»',
    category: 'warning',
    image: '/road-signs/1.20.3.png',
  },
  {
    id: '1.21',
    number: '1.21',
    name: 'Երկկողմ երթևեկություն',
    description: '1.21. «Երկկողմ երթևեկություն»',
    category: 'warning',
    image: '/road-signs/1.21.png',
  },
  {
    id: '1.22',
    number: '1.22',
    name: 'Հետիոտնային անցում',
    description: '1.22. «Հետիոտնային անցում»',
    category: 'warning',
    image: '/road-signs/1.22.png',
  },
  {
    id: '1.23',
    number: '1.23',
    name: 'Երեխաներ',
    description: '1.23. «Երեխաներ»',
    category: 'warning',
    image: '/road-signs/1.23.png',
  },
  {
    id: '1.24',
    number: '1.24',
    name: 'Հատում հեծանվային արահետի հետ',
    description: '1.24. «Հատում հեծանվային արահետի հետ»',
    category: 'warning',
    image: '/road-signs/1.24.png',
  },
  {
    id: '1.25',
    number: '1.25',
    name: 'Ճանապարհային աշխատանքներ',
    description: '1.25. «Ճանապարհային աշխատանքներ»',
    category: 'warning',
    image: '/road-signs/1.25.png',
  },
  {
    id: '1.26',
    number: '1.26',
    name: 'Անասունների քշում',
    description: '1.26. «Անասունների քշում»',
    category: 'warning',
    image: '/road-signs/1.26.png',
  },
  {
    id: '1.27',
    number: '1.27',
    name: 'Վայրի կենդանիներ',
    description: '1.27. «Վայրի կենդանիներ»',
    category: 'warning',
    image: '/road-signs/1.27.png',
  },
  {
    id: '1.28',
    number: '1.28',
    name: 'Քարերի անկում',
    description: '1.28. «Քարերի անկում»',
    category: 'warning',
    image: '/road-signs/1.28.png',
  },
  {
    id: '1.29',
    number: '1.29',
    name: 'Կողային քամի',
    description: '1.29. «Կողային քամի»',
    category: 'warning',
    image: '/road-signs/1.29.png',
  },
  {
    id: '1.30',
    number: '1.30',
    name: 'Ցածրաթռիչք ինքնաթիռներ',
    description: '1.30. «Ցածրաթռիչք ինքնաթիռներ»',
    category: 'warning',
    image: '/road-signs/1.30.png',
  },
  {
    id: '1.31',
    number: '1.31',
    name: 'Թունել',
    description: '1.31. «Թունել»',
    category: 'warning',
    image: '/road-signs/1.31.png',
  },
  {
    id: '1.32',
    number: '1.32',
    name: 'Խցանում',
    description: '1.32. «Խցանում»',
    category: 'warning',
    image: '/road-signs/1.32.png',
  },
  {
    id: '1.33',
    number: '1.33',
    name: 'Այլ վտանգներ',
    description: '1.33. «Այլ վտանգներ»',
    category: 'warning',
    image: '/road-signs/1.33.png',
  },
  {
    id: '1.34.1',
    number: '1.34.1',
    name: 'Շրջադարձի ուղղություն',
    description: '1.34.1«Շրջադարձի ուղղություն»',
    category: 'warning',
    image: '/road-signs/1.34.1.png',
  },
  {
    id: '1.34.2',
    number: '1.34.2',
    name: 'Շրջադարձի ուղղություն',
    description: '1.34.2«Շրջադարձի ուղղություն»',
    category: 'warning',
    image: '/road-signs/1.34.2.png',
  },
  {
    id: '1.34.3',
    number: '1.34.3',
    name: 'Շրջադարձի ուղղություն',
    description: '1.34.3«Շրջադարձի ուղղություն»',
    category: 'warning',
    image: '/road-signs/1.34.3.png',
  },
  {
    id: '1.35',
    number: '1.35',
    name: 'Խաչմերուկի տարածք',
    description: '1.35. «Խաչմերուկի տարածք»',
    category: 'warning',
    image: '/road-signs/1.35.png',
  },

  // 2. ԱՌԱՎԵԼՈՒԹՅԱՆ ՆՇԱՆՆԵՐ
  {
    id: '2.1',
    number: '2.1',
    name: 'Գլխավոր ճանապարհ',
    description: '2.1. «Գլխավոր ճանապարհ»',
    category: 'priority',
    image: '/road-signs/2.1.png',
  },
  {
    id: '2.2',
    number: '2.2',
    name: 'Գլխավոր ճանապարհի վերջ',
    description: '2.2. «Գլխավոր ճանապարհի վերջ»',
    category: 'priority',
    image: '/road-signs/2.2.png',
  },
  {
    id: '2.3.1',
    number: '2.3.1',
    name: 'Հատում երկրորդական ճանապարհի հետ',
    description: '2.3.1. «Հատում երկրորդական ճանապարհի հետ»',
    category: 'priority',
    image: '/road-signs/2.3.1.png',
  },
  {
    id: '2.3.2',
    number: '2.3.2',
    name: 'Երկրորդական ճանապարհի հարում',
    description: '2.3.2. «Երկրորդական ճանապարհի հարում»',
    category: 'priority',
    image: '/road-signs/2.3.2.png',
  },
  {
    id: '2.3.3',
    number: '2.3.3',
    name: 'Երկրորդական ճանապարհի հարում',
    description: '2.3.3. «Երկրորդական ճանապարհի հարում»',
    category: 'priority',
    image: '/road-signs/2.3.3.png',
  },
  {
    id: '2.3.4',
    number: '2.3.4',
    name: 'Երկրորդական ճանապարհի հարում',
    description: '2.3.4. «Երկրորդական ճանապարհի հարում»',
    category: 'priority',
    image: '/road-signs/2.3.4.png',
  },
  {
    id: '2.3.5',
    number: '2.3.5',
    name: 'Երկրորդական ճանապարհի հարում',
    description: '2.3.5. «Երկրորդական ճանապարհի հարում»',
    category: 'priority',
    image: '/road-signs/2.3.5.png',
  },
  {
    id: '2.3.6',
    number: '2.3.6',
    name: 'Երկրորդական ճանապարհի հարում',
    description: '2.3.6. «Երկրորդական ճանապարհի հարում»',
    category: 'priority',
    image: '/road-signs/2.3.6.png',
  },
  {
    id: '2.3.7',
    number: '2.3.7',
    name: 'Երկրորդական ճանապարհի հարում',
    description: '2.3.7. «Երկրորդական ճանապարհի հարում»',
    category: 'priority',
    image: '/road-signs/2.3.7.png',
  },
  {
    id: '2.4',
    number: '2.4',
    name: 'Զիջեք ճանապարհը',
    description: '2.4. «Զիջեք ճանապարհը»',
    category: 'priority',
    image: '/road-signs/2.4.png',
  },
  {
    id: '2.5',
    number: '2.5',
    name: 'Երթևեկությունն առանց կանգառի արգելվում է',
    description: '2.5. «Երթևեկությունն առանց կանգառի արգելվում է»',
    category: 'priority',
    image: '/road-signs/2.5.png',
  },
  {
    id: '2.6',
    number: '2.6',
    name: 'Հանդիպակաց երթևեկության առավելություն',
    description: '2.6. «Հանդիպակաց երթևեկության առավելություն»',
    category: 'priority',
    image: '/road-signs/2.6.png',
  },
  {
    id: '2.7',
    number: '2.7',
    name: 'Առավելություն հանդիպակաց երթևեկության նկատմամբ',
    description: '2.7. «Առավելություն հանդիպակաց երթևեկության նկատմամբ»',
    category: 'priority',
    image: '/road-signs/2.7.png',
  },

  // 3. ԱՐԳԵԼՈՂ ՆՇԱՆՆԵՐ
  {
    id: '3.1',
    number: '3.1',
    name: 'Մուտքն արգելվում է',
    description: '3.1. «Մուտքն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.1.png',
  },
  {
    id: '3.2',
    number: '3.2',
    name: 'Երթևեկությունն արգելվում է',
    description: '3.2. «Երթևեկությունն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.2.png',
  },
  {
    id: '3.3',
    number: '3.3',
    name: 'Մեխանիկական տրանսպորտային միջոցների երթևեկությունն արգելվում է',
    description:
      '3.3. «Մեխանիկական տրանսպորտային միջոցների երթևեկությունն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.3.png',
  },
  {
    id: '3.4',
    number: '3.4',
    name: 'Բեռնատար ավտոմոբիլների երթևեկությունն արգելվում է',
    description: '3.4. «Բեռնատար ավտոմոբիլների երթևեկությունն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.4.png',
  },
  {
    id: '3.5',
    number: '3.5',
    name: 'Մոտոցիկլների երթևեկությունն արգելվում է',
    description: '3.5. «Մոտոցիկլների երթևեկությունն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.5.png',
  },
  {
    id: '3.6',
    number: '3.6',
    name: 'Տրակտորների երթևեկությունն արգելվում է',
    description: '3.6. «Տրակտորների երթևեկությունն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.6.png',
  },
  {
    id: '3.7',
    number: '3.7',
    name: 'Կցորդով երթևեկությունն արգելվում է',
    description: '3.7. «Կցորդով երթևեկությունն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.7.png',
  },
  {
    id: '3.8',
    number: '3.8',
    name: 'Լծասայլերի երթևեկությունն արգելվում է',
    description: '3.8. «Լծասայլերի երթևեկությունն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.8.png',
  },
  {
    id: '3.9',
    number: '3.9',
    name: 'Հեծանիվներով երթևեկությունն արգելվում է',
    description: '3.9. «Հեծանիվներով երթևեկությունն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.9.png',
  },
  {
    id: '3.10',
    number: '3.10',
    name: 'Հետիոտների տեղաշարժն արգելվում է',
    description: '3.10. «Հետիոտների տեղաշարժն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.10.png',
  },
  {
    id: '3.11',
    number: '3.11',
    name: 'Զանգվածի սահմանափակում',
    description: '3.11. «Զանգվածի սահմանափակում»',
    category: 'prohibitory',
    image: '/road-signs/3.11.png',
  },
  {
    id: '3.12',
    number: '3.12',
    name: 'Սռնու վրա բեռնվածության սահմանափակում',
    description: '3.12. «Սռնու վրա բեռնվածության սահմանափակում»',
    category: 'prohibitory',
    image: '/road-signs/3.12.png',
  },
  {
    id: '3.13',
    number: '3.13',
    name: 'Բարձրության սահմանափակում',
    description: '3.13. «Բարձրության սահմանափակում»',
    category: 'prohibitory',
    image: '/road-signs/3.13.png',
  },
  {
    id: '3.14',
    number: '3.14',
    name: 'Լայնության սահմանափակում',
    description: '3.14. «Լայնության սահմանափակում»',
    category: 'prohibitory',
    image: '/road-signs/3.14.png',
  },
  {
    id: '3.15',
    number: '3.15',
    name: 'Երկարության սահմանափակում',
    description: '3.15. «Երկարության սահմանափակում»',
    category: 'prohibitory',
    image: '/road-signs/3.15.png',
  },
  {
    id: '3.16',
    number: '3.16',
    name: 'Նվազագույն միջտարածության սահմանափակում',
    description: '3.16. «Նվազագույն միջտարածության սահմանափակում»',
    category: 'prohibitory',
    image: '/road-signs/3.16.png',
  },
  {
    id: '3.17.1',
    number: '3.17.1',
    name: 'Մաքսային կետ',
    description: '3.17.1. «Մաքսային կետ»',
    category: 'prohibitory',
    image: '/road-signs/3.17.1.png',
  },
  {
    id: '3.17.2',
    number: '3.17.2',
    name: 'Վտանգ',
    description: '3.17.2. «Վտանգ»',
    category: 'prohibitory',
    image: '/road-signs/3.17.2.png',
  },
  {
    id: '3.17.3',
    number: '3.17.3',
    name: 'Հսկիչ կետ',
    description: '3.17.3. «Հսկիչ կետ»',
    category: 'prohibitory',
    image: '/road-signs/3.17.3.png',
  },
  {
    id: '3.18.1',
    number: '3.18.1',
    name: 'Աջ շրջադարձն արգելվում է',
    description: '3.18.1. «Աջ շրջադարձն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.18.1.png',
  },
  {
    id: '3.18.2',
    number: '3.18.2',
    name: 'Ձախ շրջադարձն արգելվում է',
    description: '3.18.2. «Ձախ շրջադարձն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.18.2.png',
  },
  {
    id: '3.19',
    number: '3.19',
    name: 'Հետադարձն արգելվում է',
    description: '3.19. «Հետադարձն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.19.png',
  },
  {
    id: '3.20',
    number: '3.20',
    name: 'Վազանցն արգելվում է',
    description: '3.20. «Վազանցն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.20.png',
  },
  {
    id: '3.21',
    number: '3.21',
    name: 'Վազանցի արգելման գոտու վերջ',
    description: '3.21. «Վազանցի արգելման գոտու վերջ»',
    category: 'prohibitory',
    image: '/road-signs/3.21.png',
  },
  {
    id: '3.22',
    number: '3.22',
    name: 'Բեռնատար ավտոմոբիլներով վազանցն արգելվում է',
    description: '3.22. «Բեռնատար ավտոմոբիլներով վազանցն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.22.png',
  },
  {
    id: '3.23',
    number: '3.23',
    name: 'Բեռնատար ավտոմոբիլներով վազանցի արգելման գոտու վերջ',
    description: '3.23. «Բեռնատար ավտոմոբիլներով վազանցի արգելման գոտու վերջ»',
    category: 'prohibitory',
    image: '/road-signs/3.23.png',
  },
  {
    id: '3.24',
    number: '3.24',
    name: 'Առավելագույն արագության սահմանափակում',
    description: '3.24. «Առավելագույն արագության սահմանափակում»',
    category: 'prohibitory',
    image: '/road-signs/3.24.png',
  },
  {
    id: '3.25',
    number: '3.25',
    name: 'Առավելագույն արագության սահմանափակման գոտու վերջ',
    description: '3.25. «Առավելագույն արագության սահմանափակման գոտու վերջ»',
    category: 'prohibitory',
    image: '/road-signs/3.25.png',
  },
  {
    id: '3.26',
    number: '3.26',
    name: 'Ձայնային ազդանշան տալն արգելվում է',
    description: '3.26. «Ձայնային ազդանշան տալն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.26.png',
  },
  {
    id: '3.27',
    number: '3.27',
    name: 'Կանգառն արգելվում է',
    description: '3.27. «Կանգառն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.27.png',
  },
  {
    id: '3.28',
    number: '3.28',
    name: 'Կայանելն արգելվում է',
    description: '3.28. «Կայանելն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.28.png',
  },
  {
    id: '3.29',
    number: '3.29',
    name: 'Կայանելն արգելվում է ամսվա կենտ օրերին',
    description: '3.29. «Կայանելն արգելվում է ամսվա կենտ օրերին»',
    category: 'prohibitory',
    image: '/road-signs/3.29.png',
  },
  {
    id: '3.30',
    number: '3.30',
    name: 'Կայանելն արգելվում է ամսվա զույգ օրերին',
    description: '3.30. «Կայանելն արգելվում է ամսվա զույգ օրերին»',
    category: 'prohibitory',
    image: '/road-signs/3.30.png',
  },
  {
    id: '3.31',
    number: '3.31',
    name: 'Բոլոր սահմանափակումների գոտու վերջ',
    description: '3.31. «Բոլոր սահմանափակումների գոտու վերջ»',
    category: 'prohibitory',
    image: '/road-signs/3.31.png',
  },
  {
    id: '3.32',
    number: '3.32',
    name: 'Վտանգավոր բեռներով տրանսպորտային միջոցների երթևեկությունն արգելվում է',
    description:
      '3.32. «Վտանգավոր բեռներով տրանսպորտային միջոցների երթևեկությունն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.32.png',
  },
  {
    id: '3.33',
    number: '3.33',
    name: 'Պայթուցիկ և դյուրավառ բեռներով տրանսպորտային միջոցների երթևեկությունն արգելվում է',
    description:
      '3.33. «Պայթուցիկ և դյուրավառ բեռներով տրանսպորտային միջոցների երթևեկությունն արգելվում է»',
    category: 'prohibitory',
    image: '/road-signs/3.33.png',
  },

  // 4. ԹԵԼԱԴՐՈՂ ՆՇԱՆՆԵՐ
  {
    id: '4.1.1',
    number: '4.1.1',
    name: 'Երթևեկությունն ուղիղ',
    description: '4.1.1. «Երթևեկությունն ուղիղ»',
    category: 'mandatory',
    image: '/road-signs/4.1.1.png',
  },
  {
    id: '4.1.2',
    number: '4.1.2',
    name: 'Երթևեկությունը դեպի աջ',
    description: '4.1.2. «Երթևեկությունը դեպի աջ»',
    category: 'mandatory',
    image: '/road-signs/4.1.2.png',
  },
  {
    id: '4.1.3',
    number: '4.1.3',
    name: 'Երթևեկությունը դեպի ձախ',
    description: '4.1.3. «Երթևեկությունը դեպի ձախ»',
    category: 'mandatory',
    image: '/road-signs/4.1.3.png',
  },
  {
    id: '4.1.4',
    number: '4.1.4',
    name: 'Երթևեկությունն ուղիղ կամ դեպի աջ',
    description: '4.1.4. «Երթևեկությունն ուղիղ կամ դեպի աջ»',
    category: 'mandatory',
    image: '/road-signs/4.1.4.png',
  },
  {
    id: '4.1.5',
    number: '4.1.5',
    name: 'Երթևեկությունն ուղիղ կամ դեպի ձախ',
    description: '4.1.5. «Երթևեկությունն ուղիղ կամ դեպի ձախ»',
    category: 'mandatory',
    image: '/road-signs/4.1.5.png',
  },
  {
    id: '4.1.6',
    number: '4.1.6',
    name: 'Երթևեկությունը դեպի աջ կամ դեպի ձախ',
    description: '4.1.6. «Երթևեկությունը դեպի աջ կամ դեպի ձախ»',
    category: 'mandatory',
    image: '/road-signs/4.1.6.png',
  },
  {
    id: '4.2.1',
    number: '4.2.1',
    name: 'Արգելքի շրջանցումն աջից',
    description: '4.2.1. «Արգելքի շրջանցումն աջից»',
    category: 'mandatory',
    image: '/road-signs/4.2.1.png',
  },
  {
    id: '4.2.2',
    number: '4.2.2',
    name: 'Արգելքի շրջանցումը ձախից',
    description: '4.2.2. «Արգելքի շրջանցումը ձախից»',
    category: 'mandatory',
    image: '/road-signs/4.2.2.png',
  },
  {
    id: '4.2.3',
    number: '4.2.3',
    name: 'Արգելքի շրջանցումն աջից կամ ձախից',
    description: '4.2.3. «Արգելքի շրջանցումն աջից կամ ձախից»',
    category: 'mandatory',
    image: '/road-signs/4.2.3.png',
  },
  {
    id: '4.3',
    number: '4.3',
    name: 'Շրջանաձև երթևեկություն',
    description: '4.3. «Շրջանաձև երթևեկություն»',
    category: 'mandatory',
    image: '/road-signs/4.3.png',
  },
  {
    id: '4.4.1',
    number: '4.4.1',
    name: 'Հեծանվային արահետ',
    description: '4.4.1 «Հեծանվային արահետ»',
    category: 'mandatory',
    image: '/road-signs/4.4.1.png',
  },
  {
    id: '4.4.2',
    number: '4.4.2',
    name: 'Հեծանվային արահետի վերջ',
    description: '4.4.2 «Հեծանվային արահետի վերջ»',
    category: 'mandatory',
    image: '/road-signs/4.4.2.png',
  },
  {
    id: '4.5.1',
    number: '4.5.1',
    name: 'Հետիոտնային արահետ',
    description: '4.5.1 «Հետիոտնային արահետ»',
    category: 'mandatory',
    image: '/road-signs/4.5.1.png',
  },
  {
    id: '4.5.2',
    number: '4.5.2',
    name: 'Համատեղ երթևեկությամբ հետիոտնային և հեծանվային արահետ ',
    description:
      '4.5.2 «Համատեղ երթևեկությամբ հետիոտնային և հեծանվային արահետ »',
    category: 'mandatory',
    image: '/road-signs/4.5.2.png',
  },
  {
    id: '4.5.3',
    number: '4.5.3',
    name: 'Համատեղ երթևեկությամբ հետիոտնային և հեծանվային արահետի վերջ',
    description:
      '4.5.3 «Համատեղ երթևեկությամբ հետիոտնային և հեծանվային արահետի վերջ»',
    category: 'mandatory',
    image: '/road-signs/4.5.3.png',
  },
  {
    id: '4.5.4',
    number: '4.5.4',
    name: 'Տարանջատված երթևեկությամբ հետիոտնային և հեծանվային արահետ',
    description:
      '4.5.4 «Տարանջատված երթևեկությամբ հետիոտնային և հեծանվային արահետ»',
    category: 'mandatory',
    image: '/road-signs/4.5.4.png',
  },
  {
    id: '4.5.5',
    number: '4.5.5',
    name: 'Տարանջատված երթևեկությամբ հետիոտնային և հեծանվային արահետ',
    description:
      '4.5.5. «Տարանջատված երթևեկությամբ հետիոտնային և հեծանվային արահետ»',
    category: 'mandatory',
    image: '/road-signs/4.5.5.png',
  },
  {
    id: '4.5.6',
    number: '4.5.6',
    name: 'Տարանջատված երթևեկությամբ հետիոտնային և հեծանվային արահետի վերջ',
    description:
      '4.5.6 «Տարանջատված երթևեկությամբ հետիոտնային և հեծանվային արահետի վերջ»',
    category: 'mandatory',
    image: '/road-signs/4.5.6.png',
  },
  {
    id: '4.5.7',
    number: '4.5.7',
    name: 'Տարանջատված երթևեկությամբ հետիոտնային և հեծանվային արահետի վերջ',
    description:
      '4.5.7. «Տարանջատված երթևեկությամբ հետիոտնային և հեծանվային արահետի վերջ»',
    category: 'mandatory',
    image: '/road-signs/4.5.7.png',
  },
  {
    id: '4.6',
    number: '4.6',
    name: 'Նվազագույն արագության սահմանափակում',
    description: '4.6. «Նվազագույն արագության սահմանափակում»',
    category: 'mandatory',
    image: '/road-signs/4.6.png',
  },
  {
    id: '4.7',
    number: '4.7',
    name: 'Նվազագույն արագության սահմանափակման գոտու վերջ',
    description: '4.7. «Նվազագույն արագության սահմանափակման գոտու վերջ»',
    category: 'mandatory',
    image: '/road-signs/4.7.png',
  },
  {
    id: '4.8.1',
    number: '4.8.1',
    name: 'Վտանգավոր բեռներով տրանսպորտային միջոցների երթևեկության ուղղություն',
    description:
      '4.8.1 «Վտանգավոր բեռներով տրանսպորտային միջոցների երթևեկության ուղղություն»',
    category: 'mandatory',
    image: '/road-signs/4.8.1.png',
  },
  {
    id: '4.8.2',
    number: '4.8.2',
    name: 'Վտանգավոր բեռներով տրանսպորտային միջոցների երթևեկության ուղղություն',
    description:
      '4.8.2 «Վտանգավոր բեռներով տրանսպորտային միջոցների երթևեկության ուղղություն»',
    category: 'mandatory',
    image: '/road-signs/4.8.2.png',
  },
  {
    id: '4.8.3',
    number: '4.8.3',
    name: 'Վտանգավոր բեռներով տրանսպորտային միջոցների երթևեկության ուղղություն',
    description:
      '4.8.3 «Վտանգավոր բեռներով տրանսպորտային միջոցների երթևեկության ուղղություն»',
    category: 'mandatory',
    image: '/road-signs/4.8.3.png',
  },

  // 5. ՀԱՏՈՒԿ ԹԵԼԱԴՐԱՆՔԻ ՆՇԱՆՆԵՐ
  {
    id: '5.1',
    number: '5.1',
    name: 'Ավտոմայրուղի',
    description: '5.1. «Ավտոմայրուղի»',
    category: 'special',
    image: '/road-signs/5.1.png',
  },
  {
    id: '5.2',
    number: '5.2',
    name: 'Ավտոմայրուղու վերջ',
    description: '5.2. «Ավտոմայրուղու վերջ»',
    category: 'special',
    image: '/road-signs/5.2.png',
  },
  {
    id: '5.3',
    number: '5.3',
    name: 'Ճանապարհ ավտոմոբիլների համար',
    description: '5.3. «Ճանապարհ ավտոմոբիլների համար»',
    category: 'special',
    image: '/road-signs/5.3.png',
  },
  {
    id: '5.4',
    number: '5.4',
    name: 'Ավտոմոբիլների համար ճանապարհի վերջ',
    description: '5.4. «Ավտոմոբիլների համար ճանապարհի վերջ»',
    category: 'special',
    image: '/road-signs/5.4.png',
  },
  {
    id: '5.5',
    number: '5.5',
    name: 'Միակողմ երթևեկությամբ ճանապարհ',
    description: '5.5. «Միակողմ երթևեկությամբ ճանապարհ»',
    category: 'special',
    image: '/road-signs/5.5.png',
  },
  {
    id: '5.6',
    number: '5.6',
    name: 'Միակողմ երթևեկությամբ ճանապարհի վերջ',
    description: '5.6. «Միակողմ երթևեկությամբ ճանապարհի վերջ»',
    category: 'special',
    image: '/road-signs/5.6.png',
  },
  {
    id: '5.7.1',
    number: '5.7.1',
    name: 'Ելք դեպի միակողմ երթևեկությամբ ճանապարհ',
    description: '5.7.1. «Ելք դեպի միակողմ երթևեկությամբ ճանապարհ»',
    category: 'special',
    image: '/road-signs/5.7.1.png',
  },
  {
    id: '5.7.2',
    number: '5.7.2',
    name: 'Ելք դեպի միակողմ երթևեկությամբ ճանապարհ',
    description: '5.7.2. «Ելք դեպի միակողմ երթևեկությամբ ճանապարհ»',
    category: 'special',
    image: '/road-signs/5.7.2.png',
  },
  {
    id: '5.8',
    number: '5.8',
    name: 'Դարձափոխային երթևեկություն',
    description: '5.8. «Դարձափոխային երթևեկություն»',
    category: 'special',
    image: '/road-signs/5.8.png',
  },
  {
    id: '5.9',
    number: '5.9',
    name: 'Դարձափոխային երթևեկության վերջ',
    description: '5.9. «Դարձափոխային երթևեկության վերջ»',
    category: 'special',
    image: '/road-signs/5.9.png',
  },
  {
    id: '5.10',
    number: '5.10',
    name: 'Ելք դեպի դարձափոխային երթևեկությամբ ճանապարհ',
    description: '5.10. «Ելք դեպի դարձափոխային երթևեկությամբ ճանապարհ»',
    category: 'special',
    image: '/road-signs/5.10.png',
  },
  {
    id: '5.11',
    number: '5.11',
    name: 'Ընդհանուր օգտագործման տրանսպորտային միջոցների համար գոտիով ճանապարհ',
    description:
      '5.11. «Ընդհանուր օգտագործման տրանսպորտային միջոցների համար գոտիով ճանապարհ»',
    category: 'special',
    image: '/road-signs/5.11.png',
  },
  {
    id: '5.12',
    number: '5.12',
    name: 'Ընդհանուր օգտագործման տրանսպորտային միջոցների համար գոտիով ճանապարհի վերջ',
    description:
      '5.12. «Ընդհանուր օգտագործման տրանսպորտային միջոցների համար գոտիով ճանապարհի վերջ»',
    category: 'special',
    image: '/road-signs/5.12.png',
  },
  {
    id: '5.13.1',
    number: '5.13.1',
    name: 'Ելք դեպի ընդհանուր օգտագործման տրանսպորտային միջոցների համար գոտիով ճանապարհ',
    description:
      '5.13.1. «Ելք դեպի ընդհանուր օգտագործման տրանսպորտային միջոցների համար գոտիով ճանապարհ»',
    category: 'special',
    image: '/road-signs/5.13.1.png',
  },
  {
    id: '5.13.2',
    number: '5.13.2',
    name: 'Ելք դեպի ընդհանուր օգտագործման տրանսպորտային միջոցների համար գոտիով ճանապարհ',
    description:
      '5.13.2. «Ելք դեպի ընդհանուր օգտագործման տրանսպորտային միջոցների համար գոտիով ճանապարհ»',
    category: 'special',
    image: '/road-signs/5.13.2.png',
  },
  {
    id: '5.14',
    number: '5.14',
    name: 'Ընդհանուր օգտագործման տրանսպորտային միջոցների համար գոտի',
    description:
      '5.14. «Ընդհանուր օգտագործման տրանսպորտային միջոցների համար գոտի»',
    category: 'special',
    image: '/road-signs/5.14.png',
  },
  {
    id: '5.15.1',
    number: '5.15.1',
    name: 'Երթևեկության ուղղությունները գոտիներով',
    description: '5.15.1. «Երթևեկության ուղղությունները գոտիներով»',
    category: 'special',
    image: '/road-signs/5.15.1.png',
  },
  {
    id: '5.15.2',
    number: '5.15.2',
    name: 'Երթևեկության ուղղությունները գոտիով',
    description: '5.15.2. «Երթևեկության ուղղությունները գոտիով»',
    category: 'special',
    image: '/road-signs/5.15.2.png',
  },
  {
    id: '5.15.3',
    number: '5.15.3',
    name: 'Գոտու սկիզբ',
    description: '5.15.3. «Գոտու սկիզբ»',
    category: 'special',
    image: '/road-signs/5.15.3.png',
  },
  {
    id: '5.15.4',
    number: '5.15.4',
    name: 'Գոտու սկիզբ',
    description: '5.15.4. «Գոտու սկիզբ»',
    category: 'special',
    image: '/road-signs/5.15.4.png',
  },
  {
    id: '5.15.5',
    number: '5.15.5',
    name: 'Գոտու վերջ',
    description: '5.15.5. «Գոտու վերջ»',
    category: 'special',
    image: '/road-signs/5.15.5.png',
  },
  {
    id: '5.15.6',
    number: '5.15.6',
    name: 'Գոտու վերջ',
    description: '5.15.6. «Գոտու վերջ»',
    category: 'special',
    image: '/road-signs/5.15.6.png',
  },
  {
    id: '5.15.7',
    number: '5.15.7',
    name: 'Երթևեկության ուղղությունը գոտիներով',
    description: '5.15.7. «Երթևեկության ուղղությունը գոտիներով»',
    category: 'special',
    image: '/road-signs/5.15.7.png',
  },
  {
    id: '5.15.8',
    number: '5.15.8',
    name: 'Գոտիների քանակը',
    description: '5.15.8. «Գոտիների քանակը»',
    category: 'special',
    image: '/road-signs/5.15.8.png',
  },
  {
    id: '5.16',
    number: '5.16',
    name: 'Ավտոբուսի և (կամ) տրոլեյբուսի կանգառի տեղ',
    description: '5.16. «Ավտոբուսի և (կամ) տրոլեյբուսի կանգառի տեղ»',
    category: 'special',
    image: '/road-signs/5.16.png',
  },
  {
    id: '5.17',
    number: '5.17',
    name: 'Տրամվայի կանգառի տեղ',
    description: '5.17. «Տրամվայի կանգառի տեղ»',
    category: 'special',
    image: '/road-signs/5.17.png',
  },
  {
    id: '5.18',
    number: '5.18',
    name: 'Թեթև մարդատար տաքսիների կայանման տեղ',
    description: '5.18. «Թեթև մարդատար տաքսիների կայանման տեղ»',
    category: 'special',
    image: '/road-signs/5.18.png',
  },
  {
    id: '5.19.1',
    number: '5.19.1',
    name: 'Հետիոտնային անցում',
    description: '5.19.1. «Հետիոտնային անցում»',
    category: 'special',
    image: '/road-signs/5.19.1.png',
  },
  {
    id: '5.19.2',
    number: '5.19.2',
    name: 'Հետիոտնային անցում',
    description: '5.19.2. «Հետիոտնային անցում»',
    category: 'special',
    image: '/road-signs/5.19.2.png',
  },
  {
    id: '5.20',
    number: '5.20',
    name: 'Արհեստական անհարթություն',
    description: '5.20. «Արհեստական անհարթություն»',
    category: 'special',
    image: '/road-signs/5.20.png',
  },
  {
    id: '5.21',
    number: '5.21',
    name: 'Բնակելի գոտի',
    description: '5.21. «Բնակելի գոտի»',
    category: 'special',
    image: '/road-signs/5.21.png',
  },
  {
    id: '5.22',
    number: '5.22',
    name: 'Բնակելի գոտու վերջ',
    description: '5.22. «Բնակելի գոտու վերջ»',
    category: 'special',
    image: '/road-signs/5.22.png',
  },
  {
    id: '5.23.1',
    number: '5.23.1',
    name: 'Բնակավայրի սկիզբ',
    description: '5.23.1. «Բնակավայրի սկիզբ»',
    category: 'special',
    image: '/road-signs/5.23.1.png',
  },
  {
    id: '5.23.2',
    number: '5.23.2',
    name: 'Բնակավայրի սկիզբ',
    description: '5.23.2. «Բնակավայրի սկիզբ»',
    category: 'special',
    image: '/road-signs/5.23.2.png',
  },
  {
    id: '5.24.1',
    number: '5.24.1',
    name: 'Բնակավայրի վերջ',
    description: '5.24.1. «Բնակավայրի վերջ»',
    category: 'special',
    image: '/road-signs/5.24.1.png',
  },
  {
    id: '5.24.2',
    number: '5.24.2',
    name: 'Բնակավայրի վերջ',
    description: '5.24.2. «Բնակավայրի վերջ»',
    category: 'special',
    image: '/road-signs/5.24.2.png',
  },
  {
    id: '5.25',
    number: '5.25',
    name: 'Բնակավայրի սկիզբ',
    description: '5.25. «Բնակավայրի սկիզբ»',
    category: 'special',
    image: '/road-signs/5.25.png',
  },
  {
    id: '5.26',
    number: '5.26',
    name: 'Բնակավայրի վերջ',
    description: '5.26. «Բնակավայրի վերջ»',
    category: 'special',
    image: '/road-signs/5.26.png',
  },
  {
    id: '5.27',
    number: '5.27',
    name: 'Կայանման սահմանափակումով գոտի',
    description: '5.27. «Կայանման սահմանափակումով գոտի»',
    category: 'special',
    image: '/road-signs/5.27.png',
  },
  {
    id: '5.28',
    number: '5.28',
    name: 'Կայանման սահմանափակումով գոտու վերջ',
    description: '5.28. «Կայանման սահմանափակումով գոտու վերջ»',
    category: 'special',
    image: '/road-signs/5.28.png',
  },
  {
    id: '5.29',
    number: '5.29',
    name: 'Կարգավորվող կայանման գոտի',
    description: '5.29. «Կարգավորվող կայանման գոտի»',
    category: 'special',
    image: '/road-signs/5.29.png',
  },
  {
    id: '5.30',
    number: '5.30',
    name: 'Կարգավորվող կայանման գոտու վերջ',
    description: '5.30. «Կարգավորվող կայանման գոտու վերջ»',
    category: 'special',
    image: '/road-signs/5.30.png',
  },
  {
    id: '5.31',
    number: '5.31',
    name: 'Առավելագույն արագության սահմանափակումով գոտի',
    description: '5.31. «Առավելագույն արագության սահմանափակումով գոտի»',
    category: 'special',
    image: '/road-signs/5.31.png',
  },
  {
    id: '5.32',
    number: '5.32',
    name: 'Առավելագույն արագության սահմանափակումով գոտու վերջ',
    description: '5.32. «Առավելագույն արագության սահմանափակումով գոտու վերջ»',
    category: 'special',
    image: '/road-signs/5.32.png',
  },
  {
    id: '5.33',
    number: '5.33',
    name: 'Հետիոտնային գոտի',
    description: '5.33. «Հետիոտնային գոտի»',
    category: 'special',
    image: '/road-signs/5.33.png',
  },

  // 6. ՏԵՂԵԿԱՏՎՈՒԹՅԱՆ ՆՇԱՆՆԵՐ
  {
    id: '6.1',
    number: '6.1',
    name: 'Առավելագույն արագության ընդհանուր սահմանափակում',
    description: '6.1. «Առավելագույն արագության ընդհանուր սահմանափակում»',
    category: 'information',
    image: '/road-signs/6.1.png',
  },
  {
    id: '6.2',
    number: '6.2',
    name: 'Առաջարկվող արագություն',
    description: '6.2. «Առաջարկվող արագություն»',
    category: 'information',
    image: '/road-signs/6.2.png',
  },
  {
    id: '6.3.1',
    number: '6.3.1',
    name: 'Հետադարձի տեղ',
    description: '6.3.1. «Հետադարձի տեղ»',
    category: 'information',
    image: '/road-signs/6.3.1.png',
  },
  {
    id: '6.3.2',
    number: '6.3.2',
    name: 'Հետադարձի գոտի',
    description: '6.3.2. «Հետադարձի գոտի»',
    category: 'information',
    image: '/road-signs/6.3.2.png',
  },
  {
    id: '6.4',
    number: '6.4',
    name: 'Կայանման տեղ',
    description: '6.4. «Կայանման տեղ»',
    category: 'information',
    image: '/road-signs/6.4.png',
  },
  {
    id: '6.5',
    number: '6.5',
    name: 'Վթարային կանգառի գոտի',
    description: '6.5. «Վթարային կանգառի գոտի»',
    category: 'information',
    image: '/road-signs/6.5.png',
  },
  {
    id: '6.6',
    number: '6.6',
    name: 'Ստորգետնյա հետիոտնային անցում',
    description: '6.6. «Ստորգետնյա հետիոտնային անցում»',
    category: 'information',
    image: '/road-signs/6.6.png',
  },
  {
    id: '6.7',
    number: '6.7',
    name: 'Վերգետնյա հետիոտնային անցում',
    description: '6.7. «Վերգետնյա հետիոտնային անցում»',
    category: 'information',
    image: '/road-signs/6.7.png',
  },
  {
    id: '6.8.1',
    number: '6.8.1',
    name: 'Փակուղի',
    description: '6.8.1. «Փակուղի»',
    category: 'information',
    image: '/road-signs/6.8.1.png',
  },
  {
    id: '6.8.2',
    number: '6.8.2',
    name: 'Փակուղի',
    description: '6.8.2. «Փակուղի»',
    category: 'information',
    image: '/road-signs/6.8.2.png',
  },
  {
    id: '6.8.3',
    number: '6.8.3',
    name: 'Փակուղի',
    description: '6.8.3. «Փակուղի»',
    category: 'information',
    image: '/road-signs/6.8.3.png',
  },
  {
    id: '6.9.1',
    number: '6.9.1',
    name: 'Ուղղությունների նախնական ցուցիչ',
    description: '6.9.1. «Ուղղությունների նախնական ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.9.1.1.png',
  },
  {
    id: '6.9.1',
    number: '6.9.1',
    name: 'Ուղղությունների նախնական ցուցիչ',
    description: '6.9.1. «Ուղղությունների նախնական ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.9.1.2.png',
  },
  {
    id: '6.9.1',
    number: '6.9.1',
    name: 'Ուղղությունների նախնական ցուցիչ',
    description: '6.9.1. «Ուղղությունների նախնական ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.9.1.3.png',
  },
  {
    id: '6.9.1',
    number: '6.9.1',
    name: 'Ուղղությունների նախնական ցուցիչ',
    description: '6.9.1. «Ուղղությունների նախնական ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.9.1.4.png',
  },
  {
    id: '6.9.2',
    number: '6.9.2',
    name: 'Ուղղությունների նախնական ցուցիչ',
    description: '6.9.2. «Ուղղությունների նախնական ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.9.2.1.png',
  },
  {
    id: '6.9.2',
    number: '6.9.2',
    name: 'Ուղղությունների նախնական ցուցիչ',
    description: '6.9.2. «Ուղղությունների նախնական ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.9.2.2.png',
  },
  {
    id: '6.9.2',
    number: '6.9.2',
    name: 'Ուղղությունների նախնական ցուցիչ',
    description: '6.9.2. «Ուղղությունների նախնական ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.9.2.3.png',
  },
  {
    id: '6.9.3',
    number: '6.9.3',
    name: 'Երթևեկության սխեմա',
    description: '6.9.3. «Երթևեկության սխեմա»',
    category: 'information',
    image: '/road-signs/6.9.3.png',
  },
  {
    id: '6.10.1',
    number: '6.10.1',
    name: 'Ուղղությունների ցուցիչ',
    description: '6.10.1. «Ուղղությունների ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.10.1.1.png',
  },
  {
    id: '6.10.1',
    number: '6.10.1',
    name: 'Ուղղությունների ցուցիչ',
    description: '6.10.1. «Ուղղությունների ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.10.1.2.png',
  },
  {
    id: '6.10.2',
    number: '6.10.2',
    name: 'Ուղղության ցուցիչ',
    description: '6.10.2. «Ուղղության ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.10.2.1.png',
  },
  {
    id: '6.10.2',
    number: '6.10.2',
    name: 'Ուղղության ցուցիչ',
    description: '6.10.2. «Ուղղության ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.10.2.2.png',
  },
  {
    id: '6.11',
    number: '6.11',
    name: 'Օբյեկտի անվանում',
    description: '6.11. «Օբյեկտի անվանում»',
    category: 'information',
    image: '/road-signs/6.11.png',
  },
  {
    id: '6.12',
    number: '6.12',
    name: 'Հեռավորությունների ցուցիչ',
    description: '6.12. «Հեռավորությունների ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.12.png',
  },
  {
    id: '6.13',
    number: '6.13',
    name: 'Կիլոմետրային նշան',
    description: '6.13. «Կիլոմետրային նշան»',
    category: 'information',
    image: '/road-signs/6.13.png',
  },
  {
    id: '6.14.2',
    number: '6.14.2',
    name: 'Երթուղու համարը',
    description: '6.14.2. «Երթուղու համարը»',
    category: 'information',
    image: '/road-signs/6.14.2.png',
  },
  {
    id: '6.15',
    number: '6.15',
    name: 'Երթևեկության ուղղություն բեռնատար ավտոմոբիլների համար',
    description:
      '6.15. «Երթևեկության ուղղություն բեռնատար ավտոմոբիլների համար»',
    category: 'information',
    image: '/road-signs/6.15.1.png',
  },
  {
    id: '6.15',
    number: '6.15',
    name: 'Երթևեկության ուղղություն բեռնատար ավտոմոբիլների համար',
    description:
      '6.15. «Երթևեկության ուղղություն բեռնատար ավտոմոբիլների համար»',
    category: 'information',
    image: '/road-signs/6.15.2.png',
  },
  {
    id: '6.15',
    number: '6.15',
    name: 'Երթևեկության ուղղություն բեռնատար ավտոմոբիլների համար',
    description:
      '6.15. «Երթևեկության ուղղություն բեռնատար ավտոմոբիլների համար»',
    category: 'information',
    image: '/road-signs/6.15.3.png',
  },
  {
    id: '6.16',
    number: '6.16',
    name: 'Կանգ-գիծ',
    description: '6.16. «Կանգ-գիծ»',
    category: 'information',
    image: '/road-signs/6.16.png',
  },
  {
    id: '6.17',
    number: '6.17',
    name: 'Շրջանցման սխեմա',
    description: '6.17. «Շրջանցման սխեմա»',
    category: 'information',
    image: '/road-signs/6.17.png',
  },
  {
    id: '6.18',
    number: '6.18',
    name: 'Շրջանցման ուղղություն',
    description: '6.18. «Շրջանցման ուղղություն»',
    category: 'information',
    image: '/road-signs/6.18.1.png',
  },
  {
    id: '6.18',
    number: '6.18',
    name: 'Շրջանցման ուղղություն',
    description: '6.18. «Շրջանցման ուղղություն»',
    category: 'information',
    image: '/road-signs/6.18.2.png',
  },
  {
    id: '6.18',
    number: '6.18',
    name: 'Շրջանցման ուղղություն',
    description: '6.18. «Շրջանցման ուղղություն»',
    category: 'information',
    image: '/road-signs/6.18.3.png',
  },
  {
    id: '6.19',
    number: '6.19',
    name: 'Այլ երթևեկելի մաս վերադասավորվելու նախնական ցուցիչ',
    description: '6.19. «Այլ երթևեկելի մաս վերադասավորվելու նախնական ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.19.1.png',
  },
  {
    id: '6.19',
    number: '6.19',
    name: 'Այլ երթևեկելի մաս վերադասավորվելու նախնական ցուցիչ',
    description: '6.19. «Այլ երթևեկելի մաս վերադասավորվելու նախնական ցուցիչ»',
    category: 'information',
    image: '/road-signs/6.19.2.png',
  },

  // 7. ՍՊԱՍԱՐԿՄԱՆ ՆՇԱՆՆԵՐ
  {
    id: '7.1',
    number: '7.1',
    name: 'Առաջին բժշկական օգնության կետ',
    description: '7.1. «Առաջին բժշկական օգնության կետ»',
    category: 'service',
    image: '/road-signs/7.1.png',
  },
  {
    id: '7.2',
    number: '7.2',
    name: 'Հիվանդանոց',
    description: '7.2. «Հիվանդանոց»',
    category: 'service',
    image: '/road-signs/7.2.png',
  },
  {
    id: '7.3',
    number: '7.3',
    name: 'Ավտոլցավորման կայան',
    description: '7.3. «Ավտոլցավորման կայան»',
    category: 'service',
    image: '/road-signs/7.3.png',
  },
  {
    id: '7.4',
    number: '7.4',
    name: 'Ավտոմոբիլների տեխնիկական սպասարկում',
    description: '7.4. «Ավտոմոբիլների տեխնիկական սպասարկում»',
    category: 'service',
    image: '/road-signs/7.4.png',
  },
  {
    id: '7.5',
    number: '7.5',
    name: 'Ավտոմոբիլների լվացում',
    description: '7.5. «Ավտոմոբիլների լվացում»',
    category: 'service',
    image: '/road-signs/7.5.png',
  },
  {
    id: '7.6',
    number: '7.6',
    name: 'Հեռախոս',
    description: '7.6. «Հեռախոս»',
    category: 'service',
    image: '/road-signs/7.6.png',
  },
  {
    id: '7.7',
    number: '7.7',
    name: 'Սննդի կետ',
    description: '7.7. «Սննդի կետ»',
    category: 'service',
    image: '/road-signs/7.7.png',
  },
  {
    id: '7.8',
    number: '7.8',
    name: 'Խմելու ջուր',
    description: '7.8. «Խմելու ջուր»',
    category: 'service',
    image: '/road-signs/7.8.png',
  },
  {
    id: '7.9',
    number: '7.9',
    name: 'Հյուրանոց կամ մոթել',
    description: '7.9. «Հյուրանոց կամ մոթել»',
    category: 'service',
    image: '/road-signs/7.9.png',
  },
  {
    id: '7.10',
    number: '7.10',
    name: 'Հանգրվան',
    description: '7.10. «Հանգրվան»',
    category: 'service',
    image: '/road-signs/7.10.png',
  },
  {
    id: '7.11',
    number: '7.11',
    name: 'Հանգստի վայր',
    description: '7.11. «Հանգստի վայր»',
    category: 'service',
    image: '/road-signs/7.11.png',
  },
  {
    id: '7.12',
    number: '7.12',
    name: 'Ճանապարհային ոստիկանության ճանապարհապարեկային ծառայության պահակետ',
    description:
      '7.12. «Ճանապարհային ոստիկանության ճանապարհապարեկային ծառայության պահակետ»',
    category: 'service',
    image: '/road-signs/7.12.png',
  },
  {
    id: '7.13',
    number: '7.13',
    name: 'Ոստիկանություն',
    description: '7.13. «Ոստիկանություն»',
    category: 'service',
    image: '/road-signs/7.13.png',
  },
  {
    id: '7.14',
    number: '7.14',
    name: 'Միջազգային ավտոմոբիլային փոխադրումների հսկման կետ',
    description: '7.14. «Միջազգային ավտոմոբիլային փոխադրումների հսկման կետ»',
    category: 'service',
    image: '/road-signs/7.14.png',
  },
  {
    id: '7.15',
    number: '7.15',
    name: 'Ճանապարհային երթևեկության մասին տեղեկություն հաղորդող ռադիոկայանի գործողության գոտի',
    description:
      '7.15. «Ճանապարհային երթևեկության մասին տեղեկություն հաղորդող ռադիոկայանի գործողության գոտի»',
    category: 'service',
    image: '/road-signs/7.15.png',
  },
  {
    id: '7.16',
    number: '7.16',
    name: 'Վթարային ծառայությունների հետ ռադիոկապի գոտի',
    description: '7.16. «Վթարային ծառայությունների հետ ռադիոկապի գոտի»',
    category: 'service',
    image: '/road-signs/7.16.png',
  },
  {
    id: '7.17',
    number: '7.17',
    name: 'Լողավազան կամ լողափ',
    description: '7.17. «Լողավազան կամ լողափ»',
    category: 'service',
    image: '/road-signs/7.17.png',
  },

  // 8. ԼՐԱՑՈՒՑԻՉ ՏԵՂԵԿԱՏՎՈՒԹՅԱՆ ՆՇԱՆՆԵՐ (ՑՈՒՑԱՆԱԿՆԵՐ)
  {
    id: '8.1.1',
    number: '8.1.1',
    name: 'Հեռավորություն մինչև օբյեկտ',
    description: '8.1.1. «Հեռավորություն մինչև օբյեկտ»',
    category: 'additional',
    image: '/road-signs/8.1.1.png',
  },
  {
    id: '8.1.2',
    number: '8.1.2',
    name: 'Հեռավորություն մինչև օբյեկտ',
    description: '8.1.2. «Հեռավորություն մինչև օբյեկտ».',
    category: 'additional',
    image: '/road-signs/8.1.2.png',
  },
  {
    id: '8.1.3',
    number: '8.1.3',
    name: 'Հեռավորություն մինչև օբյեկտ',
    description: '8.1.3. «Հեռավորություն մինչև օբյեկտ»',
    category: 'additional',
    image: '/road-signs/8.1.3.png',
  },
  {
    id: '8.1.4',
    number: '8.1.4',
    name: 'Հեռավորություն մինչև օբյեկտ',
    description: '8.1.4. «Հեռավորություն մինչև օբյեկտ»',
    category: 'additional',
    image: '/road-signs/8.1.4.png',
  },
  {
    id: '8.2.1',
    number: '8.2.1',
    name: 'Ազդման գոտի',
    description: '8.2.1. «Ազդման գոտի»',
    category: 'additional',
    image: '/road-signs/8.2.1.png',
  },
  {
    id: '8.2.2',
    number: '8.2.2',
    name: 'Ազդման գոտի',
    description: '8.2.2. «Ազդման գոտի». ',
    category: 'additional',
    image: '/road-signs/8.2.2.png',
  },
  {
    id: '8.2.3',
    number: '8.2.3',
    name: 'Ազդման գոտի',
    description: '8.2.3. «Ազդման գոտի»',
    category: 'additional',
    image: '/road-signs/8.2.3.png',
  },
  {
    id: '8.2.4',
    number: '8.2.4',
    name: 'Ազդման գոտի',
    description: '8.2.4. «Ազդման գոտի»',
    category: 'additional',
    image: '/road-signs/8.2.4.png',
  },
  {
    id: '8.2.5',
    number: '8.2.5',
    name: 'Ազդման գոտի',
    description: '8.2.5. «Ազդման գոտի»',
    category: 'additional',
    image: '/road-signs/8.2.5.png',
  },
  {
    id: '8.2.6',
    number: '8.2.6',
    name: 'Ազդման գոտի',
    description: '8.2.6. «Ազդման գոտի»',
    category: 'additional',
    image: '/road-signs/8.2.6.png',
  },
  {
    id: '8.3.1',
    number: '8.3.1',
    name: 'Ազդման ուղղություն',
    description: '8.3.1. «Ազդման ուղղություն»',
    category: 'additional',
    image: '/road-signs/8.3.1.png',
  },
  {
    id: '8.3.2',
    number: '8.3.2',
    name: 'Ազդման ուղղություն',
    description: '8.3.2. «Ազդման ուղղություն»',
    category: 'additional',
    image: '/road-signs/8.3.2.png',
  },
  {
    id: '8.3.3',
    number: '8.3.3',
    name: 'Ազդման ուղղություն',
    description: '8.3.3. «Ազդման ուղղություն»',
    category: 'additional',
    image: '/road-signs/8.3.3.png',
  },
  {
    id: '8.4.1',
    number: '8.4.1',
    name: 'Տրանսպորտային միջոցի տեսակը',
    description: '8.4.1. «Տրանսպորտային միջոցի տեսակը»',
    category: 'additional',
    image: '/road-signs/8.4.1.png',
  },
  {
    id: '8.4.2',
    number: '8.4.2',
    name: 'Տրանսպորտային միջոցի տեսակը',
    description: '8.4.2. «Տրանսպորտային միջոցի տեսակը»',
    category: 'additional',
    image: '/road-signs/8.4.2.png',
  },
  {
    id: '8.4.3',
    number: '8.4.3',
    name: 'Տրանսպորտային միջոցի տեսակը',
    description: '8.4.3. «Տրանսպորտային միջոցի տեսակը»',
    category: 'additional',
    image: '/road-signs/8.4.3.png',
  },
  {
    id: '8.4.3',
    number: '8.4.3',
    name: 'Տրանսպորտային միջոցի տեսակը',
    description: '8.4.3.1 «Տրանսպորտային միջոցի տեսակը»',
    category: 'additional',
    image: '/road-signs/8.4.3.1.png',
  },
  {
    id: '8.4.4',
    number: '8.4.4',
    name: 'Տրանսպորտային միջոցի տեսակը',
    description: '8.4.4. «Տրանսպորտային միջոցի տեսակը»',
    category: 'additional',
    image: '/road-signs/8.4.4.png',
  },
  {
    id: '8.4.5',
    number: '8.4.5',
    name: 'Տրանսպորտային միջոցի տեսակը',
    description: '8.4.5. «Տրանսպորտային միջոցի տեսակը»',
    category: 'additional',
    image: '/road-signs/8.4.5.png',
  },
  {
    id: '8.4.6',
    number: '8.4.6',
    name: 'Տրանսպորտային միջոցի տեսակը',
    description: '8.4.6. «Տրանսպորտային միջոցի տեսակը»',
    category: 'additional',
    image: '/road-signs/8.4.6.png',
  },
  {
    id: '8.4.7',
    number: '8.4.7',
    name: 'Տրանսպորտային միջոցի տեսակը',
    description: '8.4.7. «Տրանսպորտային միջոցի տեսակը»',
    category: 'additional',
    image: '/road-signs/8.4.7.png',
  },
  {
    id: '8.4.8',
    number: '8.4.8',
    name: 'Տրանսպորտային միջոցի տեսակը',
    description: '8.4.8. «Տրանսպորտային միջոցի տեսակը». ',
    category: 'additional',
    image: '/road-signs/8.4.8.png',
  },
  {
    id: '8.5.1',
    number: '8.5.1',
    name: 'Շաբաթ, կիրակի և տոն օրեր',
    description: '8.5.1. «Շաբաթ, կիրակի և տոն օրեր»',
    category: 'additional',
    image: '/road-signs/8.5.1.png',
  },
  {
    id: '8.5.2',
    number: '8.5.2',
    name: 'Աշխատանքային օրեր',
    description: '8.5.2. «Աշխատանքային օրեր»',
    category: 'additional',
    image: '/road-signs/8.5.2.png',
  },
  {
    id: '8.5.3',
    number: '8.5.3',
    name: 'Շաբաթվա օրեր',
    description: '8.5.3. «Շաբաթվա օրեր»',
    category: 'additional',
    image: '/road-signs/8.5.3.png',
  },
  {
    id: '8.5.4',
    number: '8.5.4',
    name: 'Գործողության ժամանակ',
    description: '8.5.4. «Գործողության ժամանակ»',
    category: 'additional',
    image: '/road-signs/8.5.4.png',
  },
  {
    id: '8.5.5',
    number: '8.5.5',
    name: 'Գործողության ժամանակ',
    description: '8.5.5. «Գործողության ժամանակ»',
    category: 'additional',
    image: '/road-signs/8.5.5.png',
  },
  {
    id: '8.5.6',
    number: '8.5.6',
    name: 'Գործողության ժամանակ',
    description: '8.5.6. «Գործողության ժամանակ»',
    category: 'additional',
    image: '/road-signs/8.5.6.png',
  },
  {
    id: '8.5.7',
    number: '8.5.7',
    name: 'Գործողության ժամանակ',
    description: '8.5.7. «Գործողության ժամանակ»',
    category: 'additional',
    image: '/road-signs/8.5.7.png',
  },
  {
    id: '8.6.2',
    number: '8.6.2',
    name: 'Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում',
    description:
      '8.6.2. «Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում»',
    category: 'additional',
    image: '/road-signs/8.6.2.png',
  },
  {
    id: '8.6.3',
    number: '8.6.3',
    name: 'Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում',
    description:
      '8.6.3. «Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում»',
    category: 'additional',
    image: '/road-signs/8.6.3.png',
  },
  {
    id: '8.6.4',
    number: '8.6.4',
    name: 'Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում',
    description:
      '8.6.4. «Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում»',
    category: 'additional',
    image: '/road-signs/8.6.4.png',
  },
  {
    id: '8.6.5',
    number: '8.6.5',
    name: 'Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում',
    description:
      '8.6.5. «Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում»',
    category: 'additional',
    image: '/road-signs/8.6.5.png',
  },
  {
    id: '8.6.6',
    number: '8.6.6',
    name: 'Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում',
    description:
      '8.6.6. «Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում»',
    category: 'additional',
    image: '/road-signs/8.6.6.png',
  },
  {
    id: '8.6.7',
    number: '8.6.7',
    name: 'Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում',
    description:
      '8.6.7. «Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում»',
    category: 'additional',
    image: '/road-signs/8.6.7.png',
  },
  {
    id: '8.6.8',
    number: '8.6.8',
    name: 'Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում',
    description:
      '8.6.8. «Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում»',
    category: 'additional',
    image: '/road-signs/8.6.8.png',
  },
  {
    id: '8.6.9',
    number: '8.6.9',
    name: 'Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում',
    description:
      '8.6.9. «Տրանսպորտային միջոցի կանգնեցման ձևը կայանման տեղերում»',
    category: 'additional',
    image: '/road-signs/8.6.9.png',
  },
  {
    id: '8.7',
    number: '8.7',
    name: 'Կայանում չգործարկված շարժիչով',
    description:
      '8.7. «Կայանում չգործարկված շարժիչով». ցույց է տալիս, որ 6.4` «Կայանման տեղ»',
    category: 'additional',
    image: '/road-signs/8.7.png',
  },
  {
    id: '8.8',
    number: '8.8',
    name: 'Վճարովի ծառայություններ',
    description: '8.8. «Վճարովի ծառայություններ»',
    category: 'additional',
    image: '/road-signs/8.8.png',
  },
  {
    id: '8.9',
    number: '8.9',
    name: 'Կայանման տևողության սահմանափակում',
    description:
      '8.9. «Կայանման տևողության սահմանափակում». տեղեկացնում է 6.4` «Կայանման տեղ»',
    category: 'additional',
    image: '/road-signs/8.9.png',
  },
  {
    id: '8.10',
    number: '8.10',
    name: 'Ավտոմոբիլների զննման տեղ',
    description: '8.10. «Ավտոմոբիլների զննման տեղ». ',
    category: 'additional',
    image: '/road-signs/8.10.png',
  },
  {
    id: '8.11',
    number: '8.11',
    name: 'Թույլատրելի առավելագույն զանգվածի սահմանափակում',
    description: '8.11. «Թույլատրելի առավելագույն զանգվածի սահմանափակում»',
    category: 'additional',
    image: '/road-signs/8.11.png',
  },
  {
    id: '8.12',
    number: '8.12',
    name: 'Վտանգավոր կողնակ',
    description: '8.12. «Վտանգավոր կողնակ». ',
    category: 'additional',
    image: '/road-signs/8.12.png',
  },
  {
    id: '8.13',
    number: '8.13',
    name: 'Գլխավոր ճանապարհի ուղղություն',
    description: '8.13. «Գլխավոր ճանապարհի ուղղություն»',
    category: 'additional',
    image: '/road-signs/8.13.png',
  },
  {
    id: '8.14',
    number: '8.14',
    name: 'Երթևեկության գոտի',
    description: '8.14. «Երթևեկության գոտի»',
    category: 'additional',
    image: '/road-signs/8.14.png',
  },
  {
    id: '8.15',
    number: '8.15',
    name: 'Կույր հետիոտներ',
    description: '8.15. «Կույր հետիոտներ».',
    category: 'additional',
    image: '/road-signs/8.15.png',
  },
  {
    id: '8.16',
    number: '8.16',
    name: 'Խոնավ ծածկույթ',
    description: '8.16. «Խոնավ ծածկույթ»',
    category: 'additional',
    image: '/road-signs/8.16.png',
  },
  {
    id: '8.17',
    number: '8.17',
    name: 'Հաշմանդամներ',
    description: '8.17. «Հաշմանդամներ».',
    category: 'additional',
    image: '/road-signs/8.17.png',
  },
  {
    id: '8.18',
    number: '8.18',
    name: 'Բացի հաշմանդամներից',
    description: '8.18. «Բացի հաշմանդամներից». ',
    category: 'additional',
    image: '/road-signs/8.18.png',
  },
  {
    id: '8.19',
    number: '8.19',
    name: 'Վտանգավոր բեռի դասը',
    description: '8.19. «Վտանգավոր բեռի դասը». ',
    category: 'additional',
    image: '/road-signs/8.19.png',
  },
  {
    id: '8.20.1',
    number: '8.20.1',
    name: 'Տրանսպորտային միջոցի սայլակի տեսակը',
    description: '8.20.1. «Տրանսպորտային միջոցի սայլակի տեսակը»',
    category: 'additional',
    image: '/road-signs/8.20.1.png',
  },
  {
    id: '8.20.2',
    number: '8.20.2',
    name: 'Տրանսպորտային միջոցի սայլակի տեսակը',
    description: '8.20.2. «Տրանսպորտային միջոցի սայլակի տեսակը»',
    category: 'additional',
    image: '/road-signs/8.20.2.png',
  },
  {
    id: '8.21.1',
    number: '8.21.1',
    name: 'Ընդհանուր օգտագործման տրանսպորտային միջոցի տեսակը',
    description: '8.21.1. «Ընդհանուր օգտագործման տրանսպորտային միջոցի տեսակը»',
    category: 'additional',
    image: '/road-signs/8.21.1.png',
  },
  {
    id: '8.21.2',
    number: '8.21.2',
    name: 'Ընդհանուր օգտագործման տրանսպորտային միջոցի տեսակը',
    description: '8.21.2. «Ընդհանուր օգտագործման տրանսպորտային միջոցի տեսակը»',
    category: 'additional',
    image: '/road-signs/8.21.2.png',
  },
  {
    id: '8.21.3',
    number: '8.21.3',
    name: 'Ընդհանուր օգտագործման տրանսպորտային միջոցի տեսակը',
    description: '8.21.3. «Ընդհանուր օգտագործման տրանսպորտային միջոցի տեսակը»',
    category: 'additional',
    image: '/road-signs/8.21.3.png',
  },
  {
    id: '8.22.1',
    number: '8.22.1',
    name: 'Խոչընդոտ',
    description: '8.22.1. «Խոչընդոտ»',
    category: 'additional',
    image: '/road-signs/8.22.1.png',
  },
  {
    id: '8.22.2',
    number: '8.22.2',
    name: 'Խոչընդոտ',
    description: '8.22.2. «Խոչընդոտ»',
    category: 'additional',
    image: '/road-signs/8.22.2.png',
  },
  {
    id: '8.22.3',
    number: '8.22.3',
    name: 'Խոչընդոտ',
    description: '8.22.3. «Խոչընդոտ»',
    category: 'additional',
    image: '/road-signs/8.22.3.png',
  },
  {
    id: '8.23',
    number: '8.23',
    name: 'Աշխատում է տարհանիչը',
    description: '8.23. «Աշխատում է տարհանիչը»',
    category: 'additional',
    image: '/road-signs/8.23.png',
  },
  {
    id: '8.24',
    number: '8.24',
    name: 'Ծառայողական ավտոմոբիլների համար կայանատեղ',
    description: '8.24. «Ծառայողական ավտոմոբիլների համար կայանատեղ»',
    category: 'additional',
    image: '/road-signs/8.24.png',
  },
  {
    id: '8.25',
    number: '8.25',
    name: 'Բացի ծառայողական ավտոմոբիլներից',
    description: '8.25. «Բացի ծառայողական ավտոմոբիլներից»',
    category: 'additional',
    image: '/road-signs/8.25.png',
  },
  {
    id: '8.26',
    number: '8.26',
    name: 'Զբոսաշրջային ավտոբուսների համար կայանատեղի',
    description: '8.26. «Զբոսաշրջային ավտոբուսների համար կայանատեղի»',
    category: 'additional',
    image: '/road-signs/8.26.png',
  },
  {
    id: '8.27',
    number: '8.27',
    name: 'Բացի զբոսաշրջային ավտոբուսներից',
    description: '8.27. «Բացի զբոսաշրջային ավտոբուսներից»',
    category: 'additional',
    image: '/road-signs/8.27.png',
  },
  {
    id: '8.28',
    number: '8.28',
    name: 'Շրջիկ առևտուր իրականացնող տրանսպորտային միջոցների համար կայանատեղի',
    description:
      '8.28. «Շրջիկ առևտուր իրականացնող տրանսպորտային միջոցների համար կայանատեղի»',
    category: 'additional',
    image: '/road-signs/8.28.png',
  },
];

// Helper functions
export function getAllSigns(): RoadSign[] {
  return roadSigns;
}

export function getSignsByCategory(category: RoadSign['category']): RoadSign[] {
  return roadSigns.filter((sign) => sign.category === category);
}

export function getSignById(id: string): RoadSign | undefined {
  return roadSigns.find((sign) => sign.id === id);
}

export function getSignByNumber(number: string): RoadSign | undefined {
  return roadSigns.find((sign) => sign.number === number);
}

export const categoryLabels: Record<RoadSign['category'], string> = {
  warning: 'Նախազգուշացնող',
  priority: 'Առավելության',
  prohibitory: 'Արգելող',
  mandatory: 'Թելադրող',
  special: 'Հատուկ թելադրանքի',
  information: 'Տեղեկատվության',
  service: 'Սպասարկման',
  additional: 'Լրացուցիչ տեղեկատվության',
};
